;//!
;//!
;//!    @file CVS_doxygen.inc
;//!
;//!    @brief template 
;//!     
;//!    @par DEVICE : AVR-core
;//!   
;//!    @par Licence/Copyright 
;//!        
;//!        This sources code are under GNU LGPL licence (* : see on "http://www.gnu.org/licenses/licenses.html").
;//!            - This files can be used for commercial usage and free usage.
;//!            - The files should be free*, publiched.
;//!            - This authors should be informed about modification done this.
;//!            .
;//!        
;//!        The documentation is under GNU FDL licence (* see on "http://www.gnu.org/licenses/licenses.html").
;//!        
;//!    @version $Revision: 1.2 $ $Name:  $
;//!  
;//!    @todo
;//!     
;//!    @bug
;//!   
;//!    @par CVS Info : 
;//!   
;//!\n  $Header: Y:\cvs_public/AVR/Template/CVS_doxygen.inc,v 1.2 2005/04/23 08:47:43 zoubata Exp $
;//!\n  $Date: 2005/04/23 08:47:43 $
;//!\n  $Revision: 1.2 $
;//!
;//!\n  $History: CVS_doxygen.inc $
;//!   
;//!\n 
;//!\n  $Log: CVS_doxygen.inc,v $
;//!\n  Revision 1.2  2005/04/23 08:47:43  zoubata
;//!\n  update doxygen comments
;//!\n
;//!\n  Revision 1.1  2005/04/23 08:29:15  zoubata
;//!\n  update doxygen comments
;//!\n
;//!\n  Revision 1.1  2005/04/23 08:04:04  zoubata
;//!\n  Creation of main branch
;//!\n
;//!\n

#ifndef _CVS_doxygen_inc_
#define _CVS_doxygen_inc_

/*_____ I N C L U D E - F I L E S ____________________________________________*/

/*_____ D E C L A R A T I O N ________________________________________________*/

/*_____ C O N S T A N T E S - D E F I N I T I O N  ___________________________*/

/*_____ T Y P E D E F - D E C L A R A T I O N ________________________________*/

/*_____ G L O B A L S ________________________________________________________*/

/*_____ P R O T O T Y P E S - D E C L A R A T I O N __________________________*/

/*_____ L O C A L S __________________________________________________________*/

/*_____ P U B L I C - F U N C T I O N S ______________________________________*/

/*_____ P R I V A T E - F U N C T I O N S ____________________________________*/

#endif 